### ISSUE TITLE
Duplicate Tooltips when hovering over course buttons

### ISSUE THREAD

**Issue by cewing** [jazkarta/edx-platform-for-isc#3]
In Zen Mojo 3, whenever I point the mouse/cursor at one of the buttons on the navigation bar I see double hover text; one laid on top of the other. It's actually kind of irritating.

See the attached screen capture.

![image01](https://cloud.githubusercontent.com/assets/417109/7947963/62823fde-0935-11e5-80b7-79843020958f.png)

I see this behavior too on staging and on learning. I am on Chrome.

https://learning.intersystems.com/courses/InterSystems/ISC1001/2015_1/courseware/15252fd1f3ff4a7698894a10195de3d9/3f9958a4f3fd441ba0186bdb8410f671/

https://staging-lms.learning.intersystems.com/courses/InterSystems/COS01/2015/courseware/169d0a98a2284b6691a6b51702a371ac/21bb07a3d5b04d88bf3a2a44fba98e79/

(from David and Janine)

**Comment by cewing** [comment]
from @natea:

the reason this is happening is because edX is defining the title twice, both as title= and data-page-title=

``` html
<a class="seq_other progress-0 active" data-id="i4x://InterSystems/ISC1001/vertical/dad0704ab8b04c30abca7e6b930403a7" data-element="3" href="javascript:void(0);" title="Summary" data-page-title="Summary" aria-controls="seq_contents_2" id="tab_2" tabindex="0" role="tab" aria-selected="true">
<p aria-hidden="false">Summary</p>
</a>
```

My guess is that this is for accessibility and browser compatibility reasons. People who are sight impaired will still see the title= and people who are on older browsers who won't see data-page-title= will still get the message.

But I agree that it's annoying that it appears twice. You can probably turn off those hints in your browser settings.

**Comment by cewing** [comment]
@natea, I don't think there's any clarification required here.

**Comment by chrisrossi** [comment]
Why do I keep getting these? Is someone adding me?

Chris

**Comment by cewing** [comment]
apologies, @chrisrossi, you are on a team which has ownership of this repo.  I will remove you if you like.

**Comment by bryanlandia** [comment]
@natea - I'm not sure how to reproduce this.  Can I get login credentials to learning.intersystems.com or staging-lms.intersystems.com so that I can see what David and Janine are seeing?  Not sure why they are using a screen capture from 'Zen Mojo 3'... how does that relate to the LMS?  I expected to find this behavior when rolling over tabs in a Course view in the LMS, but I don't on Chrome (albeit Chrome on Mac).  I haven't seen anything in the isc theme for LMS that generates a tabbed bar like what they show here, but maybe I don't know where to look.

I only see a tab-like presentation like this:

![screen shot 2015-06-04 at 11 15 03 am](https://cloud.githubusercontent.com/assets/1289191/7991204/4f4e7fc8-0aab-11e5-9d59-0670374f5303.png)

**Comment by bryanlandia** [comment]
@natea - Ohhhhh.... I found it.  Disregard

**Comment by bryanlandia** [comment]
Fixed in https://github.com/ISCLC/edx-theme/commit/3e96de003c1f6a37de3b89a69982afe96eb376b1

**Comment by bryanlandia** [comment]
@natea - Assigning to you to test with your staging integration.  I took a simple approach just deleting the 'title' attribute for now... there might be a way to work with (I think it's) qTip the tooltip library to delete any title attributes on tags but didn't know whether to spend time there or not. - b

**Comment by bryanlandia** [comment]
Confirmed working on isc_appsembler_dev Birch site.

**Comment by bryanlandia** [comment]
Deployed and working on staging.  Closing
