### ISSUE TITLE
ISC Customizations: Online Labs

### ISSUE THREAD

**Issue by cewing** [jazkarta/edx-platform-for-isc#8]
Port the changes in [this commit](https://github.com/jazkarta/edx-platform/commit/9f1c9c3785a0ad999e4fc2312e572bf08da9652f).

**Comment by cewing** [comment]
@natea: this too appears to be something unlikely to be accepted by edx directly.  I suppose we have little choice but to carry it along as a patch to a release tag.

**Comment by cewing** [comment]
@natea: never mind.  This can actually be included in the xblock so I'm closing this issue.

**Comment by natea** [comment]
@cewing agreed that edX will not accept this as a PR since it's very specific to ISC. This was more of an experiment to provide immediate relief for the customer to not have to copy/paste HTML/JS code into a raw HTML unit.

But I think this approach will be replaced by a dedicated XBlock for adding the online labs to an edX course.

**Comment by cewing** [comment]
yeah @natea, that's why I closed this issue in favor of #9
